### ISSUE TITLE
GroundTruth JSON Files

### ISSUE THREAD

**Issue by rastreus** [Yuppie898988/Laser-Dot-Detector#2]
Thank you for sharing this code.

How did you create the `.json` files for the GroundTruth TestSet?

I would like to create my own TestData images with GroundTruth `.json` files.

**Comment by YuxueYang1204** [comment]
You can try any annotation tools to annotate rectangles, such as [labelme](https://github.com/wkentaro/labelme).

Hope that can help you.

**Comment by rastreus** [comment]
Yes. I am new to Python so I am not as familiar with its ecosystem and tools. I will look at [labelme](https://github.com/wkentaro/labelme).

Thank you! 👍
