### ISSUE TITLE
铁铁，关于这个项目你有写论文吗，可不可以瞻仰一下你的论文，谢谢

### ISSUE THREAD

**Issue by Kwywen** [Yuppie898988/Laser-Dot-Detector#3]

**Comment by YuxueYang1204** [comment]
这是我几年前本科时期不成熟的小作品，如果您感兴趣可以进入CNKI搜索[A Laser Spot Detection Based on Boundary Point Set in Complex Indoor Scenes
](https://kns.cnki.net/kcms2/article/abstract?v=fCqJ37DMrBn58205PUV7VMjWotSjT26nuxYsQgsaPecTiTgXjB5w7C0R8zh-0UnKzfsvSSdXc-ni_OQ0O3KHa0CgnPHdO4r4xSNfZN8OGlcmNVahs-0f4Yf4EM55LQto1tM3nYpTDxfksCLqxUN2GQ==&uniplatform=NZKPT&language=CHS)
